# -*- coding: utf-8 -*-
"""Copie de Ultralytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AihyCoQ5ICPmD9FV-fx0PYiA9nbgmCZm
"""


from PIL import Image
import glob
import zipfile
import os

"""# **ULTRALYTICS**"""

import ultralytics
from ultralytics import YOLO
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

# Load a model
model = YOLO("yolo11n.pt").to(device)
print(f"Modèle chargé sur : {device}")

"""# **Entrainement**"""

#model.train(data="dataset2/data.yaml", epochs=150, cache=True, device="cuda", batch=32, imgsz=640, patience=15)
#device="cuda"

"""# **Validation**"""

# Charger le modèle entraîné
model = YOLO('runs/detect/train/weights/best.pt').to(device)
print(f"Modèle chargé sur : {device}")

# Effectuer l'évaluation sur le jeu de validation
metrics = model.val(data="dataset/dataset/data.yaml", imgsz=640, batch=32, device=device)

# Afficher les résultats des métriques
print(metrics)

"""# **Fine-Tune**"""
#!yolo task=detect mode=train model='runs/detect/train2/weights/best.pt' data='dataset2/data.yaml' imgsz=640 epochs=100 batch=32 lr0=0.01 device="cuda" optimizer='Adam' cache_images=True patience=15

